# docker-compose.yml
version: '3.8'

services:
  # Main Framework Container with Nginx
  framework:
    build: ./framework
    container_name: modular-framework
    ports:
      - "80:80"
    volumes:
      - ./framework/html:/usr/share/nginx/html
      - ./framework/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
    restart: unless-stopped

  # SSH Terminal Module Container
  ssh-terminal:
    build: ./modules/ssh-terminal
    container_name: ssh-terminal-module
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    networks:
      - app-network
    restart: unless-stopped

  github-hub-module:
    build:
      context: ./modules/github-hub
    container_name: github-hub-module
    environment:
      - PORT=3005
      # OPTIONAL: 32-byte urlsafe base64 Fernet key (keeps PAT encrypted at rest)
      # Generate once: python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GH_TOKEN_KEY=${GH_TOKEN_KEY}
      - DATA_DIR=/data
    volumes:
      - ./modules/github-hub/data:/data
    expose:
      - "3005"
    networks:
      - app-network
  llm-chat:
    build: ./modules/llm-chat
    container_name: llm-chat-module
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=production
      - PORT=3004
    networks:
      - app-network
    restart: unless-stopped

  openvscode-module:
      build: ./modules/openvscode
      container_name: openvscode-module
      ports:
        - "3006:3006"
        - "3007:3007"
      volumes:
        - ./modules/openvscode/workspaces:/home/workspace
        - /var/run/docker.sock:/var/run/docker.sock
      environment:
        - WORKSPACE_DIR=/home/workspace
        - PORT=3006
        - API_PORT=3007
      networks:
        - app-network
      depends_on:
        - github-hub-module
        - llm-chat

  # Additional Module Examples (can be uncommented)
  # code-editor:
  #   build: ./modules/code-editor
  #   container_name: code-editor-module
  #   ports:
  #     - "3002:3002"
  #   networks:
  #     - app-network
  
  # git-viewer:
  #   build: ./modules/git-viewer
  #   container_name: git-viewer-module
  #   ports:
  #     - "3003:3003"
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge